# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
#都可以得到相同的結果

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件
import numpy as np


In [5]:
A = np.random.random((5, 5))

_A = np.max(A) - np.min(A)
print((A - np.min(A)) / _A)

[[0.0835587  0.93655238 0.19566344 0.88642004 0.93123745]
 [0.14593723 0.78208921 0.31969899 0.47788032 0.29086806]
 [1.         0.66259916 0.98055238 0.6924087  0.2502506 ]
 [0.15760979 0.2189035  0.090979   0.8764394  0.71148411]
 [0.         0.72313027 0.79492483 0.26506046 0.70201855]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [10]:
B = np.random.randint(1,100,10)
maxB = B.max
B[np.argmax(B)] = -1

print(B)

[50 63 71 29 -1 33 35 18 20  8]
